configure_dotfiles: true
dotfiles_repo: https://github.com/nidomiro/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/workspace/nidomiro.de/dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .gnupg/gpg.conf
  - .gnupg/gpg-agent.conf
  - .profile
  - .shell/common.sh
  - .shell/linux.sh
#  - .vimrc

pip_install_packages:
  - name: docker
  - name: docker-compose
  - name: virtualenv
  - name: PyMySQL
  - name: psycopg2-binary

apt_repositories:
  - repo: "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable"
    filename: syncthing
  - repo: "ppa:yubico/stable"
    filename: yubico
  - repo: "ppa:phoerious/keepassxc"
    filename: keepassxc

install_packages:
#  - maven
  - gimp
  - python3-pip
  - firefox
  - thunderbird
  - kmymoney
  - vim
  - rsync
  - exfatprogs
  - syncthing
  - mkvtoolnix
  - mkvtoolnix-gui
  - flatpak
  - yubikey-manager
  - yubikey-personalization-gui
  - kdiff3
  - keepassxc
  - kleopatra
  - filelight

apt_packages:
  - build-essential
  - exfat-fuse
  - printer-driver-gutenprint
  - syncthing-gtk
  - plasma-discover-backend-flatpak
  - scdaemon
  - libpam-yubico
  - libpam-u2f
  - synaptic
  - steam

dnf_packages:
  - fedora-workstation-repositories
  - pam_yubico
  - pam-u2f
  - pamu2fcfg
  - yubikey-manager-qt
  #- yubioath-desktop
  - nextcloud-client

additional_yum_repositories:
  - url: https://packages.microsoft.com/yumrepos/vscode
    name: Visual Studio Code
    id: vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc


dnf_packages_after_repo_enable:
  - steam
  - code
  - code-insiders



flatpak_system_packages:
  - com.github.tchx84.Flatseal
  - com.heroicgameslauncher.hgl
  - md.obsidian.Obsidian
  - net.davidotek.pupgui2
  - org.kde.ktouch
  - org.openscad.OpenSCAD
  - com.spotify.Client
  - com.todoist.Todoist
  - com.google.Chrome

flatpak_user_packages: []

snap_packages:
#  - spotify
#  - todoist

snap_packages_classic: []

nvm_install_node_versions:
  - 16
  - 18

nvm_default_node_version: 18

global_npm_packages:
  - pnpm
  - nx


# TODO: configure nextcloud sync folders (`~/.config/Nextcloud/nextcloud.cfg` + target folder creation) via ansible?
# TODO: add Jetbrains Mono Font?
# TODO: add ~~Virtualbox?~~ => kvm
# TODO: add restic (sudo bash -c "curl -s -L https://github.com/restic/restic/releases/download/v0.15.2/restic_0.15.2_linux_amd64.bz2 | bunzip2 > /bin/restic && chmod +x /bin/restic")

# TODO: install ubuntu vscode from deb, as snap does not have access to gpg. downloadLink: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
# TODO: install ubuntu vscode-insider from deb, as snap does not have access to gpg. downloadLink: https://code.visualstudio.com/sha/download?build=insider&os=linux-deb-x64

# TODO: Configure KDE

# TODO: install nextcloud client
