---
- hosts: all

  vars_files:
    - config.yml

  vars:
    my_user: "{{ ansible_user_id }}"


  pre_tasks:
    - name: Make sure the needed directories exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/.gnupg
        - ~/.shell
        - ~/bin

  tasks:
    - name: Run tasks/update_and_apt_packages.yml
      include_tasks: "tasks/update_and_apt_packages.yml"

    - name: Run tasks/install_docker.yml
      include_tasks: "tasks/install_docker.yml"

    - name: Install Dotfiles
      ansible.builtin.include_role:
        name: geerlingguy.dotfiles
        
    - name: Copy bin
      ansible.builtin.copy:
        src: home/bin/
        dest: ~/bin/
        
