---
- hosts: all

  vars_files:
    - config.yml

  vars:
    my_user: "{{ ansible_user_id }}"

  handlers:
    - name: Update font cache
      become: true
      ansible.builtin.shell: fc-cache -v

  pre_tasks:
    - name: Make sure the needed directories exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/.gnupg
        - ~/.shell
        - ~/bin
        - ~/.fonts

  tasks:
    - include_tasks: "tasks/update_and_install_packages.yml"

    - include_tasks: "tasks/install_docker.yml"

    - include_tasks: "tasks/setup_dotfiles.yml"
      when: configure_dotfiles

    - name: Copy bin
      ansible.builtin.copy:
        src: home/bin/
        dest: ~/bin/

    - include_tasks: "tasks/install_flatpack_apps.yml"

    #- name: Run tasks/install_snap_apps.yml
    #  include_tasks: "tasks/install_snap_apps.yml"

    - include_tasks: "tasks/install_fnm_and_node.yml"

    - include_tasks: "tasks/install_deno.yml"

    #- name: Run tasks/setup_yubikey.yml
    #  include_tasks: "tasks/setup_yubikey.yml"

    - include_tasks: "tasks/fonts/install_fonts.yml"
