---
- hosts: all

  vars_files:
    - config.yml

  vars:
    my_user: "{{ ansible_user_id }}"


  pre_tasks:
    - name: Make sure the needed directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: niclas
        group: niclas
        mode: u+rw,g+rw,o-rwx
      loop:
        - ~/.gnupg
        - ~/.shell


    - name: Update apt-cache
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Update system
      become: true
      apt:
        upgrade: full
        autoremove: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Install Apt Packages
      become: true
      apt:
        pkg: "{{apt_packages}}"
        state: latest
        update_cache: true


  roles:
    - role: geerlingguy.git
      become: true

    - role: geerlingguy.pip
      become: true

    - role: geerlingguy.docker
      become: true

    - role: geerlingguy.dotfiles
      become: false
      when: configure_dotfiles
      tags: [ 'dotfiles' ]

  tasks:
    - name: Make sure user '{{ my_user }}' is in docker group
      ansible.builtin.user:
        name: "{{ my_user }}"
        append: True
        groups: docker