---
roles:
  - name: geerlingguy.dotfiles
    version: 1.2.1
  - name: geerlingguy.git
    version: 3.0.0
  - name: geerlingguy.pip
    version: 2.1.0
  - name: geerlingguy.docker
    version: 4.2.2

collections:
  - name: community.general
  - name: community.docker
