---
- name: Install Docker
  ansible.builtin.include_role:
    name: geerlingguy.docker
    apply:
      become: true

- name: Make sure user '{{ my_user }}' is in docker group
  become: true
  ansible.builtin.user:
    name: "{{ my_user }}"
    append: True
    groups: docker

- name: copy daemon.json
  become: true
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/tasks/install_docker/daemon.json"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
