---


- name: install deno
  shell: >
    curl -fsSL https://deno.land/install.sh | sh
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.deno/"

