---


- name: Install snap packages
  become: true
  community.general.snap:
    name: "{{ snap_packages }}"
    state: present

- name: Install snap packages (classic)
  become: true
  community.general.snap:
    name: "{{ item }}"
    classic: true
    state: present
  loop: "{{ snap_packages_classic }}"
