---

- name: Download syncthing gpg key
  become: true
  ansible.builtin.get_url:
    url: https://syncthing.net/release-key.gpg
    dest: /usr/share/keyrings/syncthing-archive-keyring.gpg

- name: Add apt-repositories
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.filename }}"
  loop: "{{ apt_repositories }}"


- name: Update apt-cache
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Update system
  become: true
  apt:
    upgrade: full
    autoremove: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Install Apt Packages
  become: true
  apt:
    pkg: "{{apt_packages}}"
    state: latest
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Install git
  ansible.builtin.include_role:
    name: geerlingguy.git
    apply:
      become: true

- name: Install pip packages
  ansible.builtin.include_role:
    name: geerlingguy.pip
    apply:
      become: true